name: Test

on:
  pull_request:

jobs:
  build:
    name: Test ${{ matrix.arch }}-${{ matrix.release }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release:
          - 23.05.3

        arch:
          - aarch64_cortex-a53


    steps:
      - uses: actions/checkout@v3

      - name: Add test directories
        run: mkdir artifacts feed

      - name: Build
        uses: ./
        env:
          ARCH: ${{ matrix.arch }}-${{ matrix.release }}
          ARTIFACTS_DIR: ${{ github.workspace }}/artifacts
          FEED_DIR: ${{ github.workspace }}/feed
          PACKAGES: dnsmasq-full vim

      - name: Verify packages saved
        run: find artifacts/bin/packages/${{ matrix.arch }}/packages/ -maxdepth 1 -name '*.ipk' -type f | grep .

      - name: Verify logs saved
        run: find artifacts/logs/package/feeds/packages/ -mindepth 2 -maxdepth 2 -name compile.txt -type f | grep .
